/**
 * Builds dist/tokens.css and dist/tokens.json from tokens/**.json, and the two
 * views of the semantic tier for Tailwind and React Native (scripts/outputs.mjs).
 *
 *   node scripts/build.mjs          write the files
 *   node scripts/build.mjs --check  fail if the committed files are stale
 *
 * dist/ is committed on purpose: generated CSS is reviewed in pull requests,
 * and CI runs --check so the JSON source and the CSS never drift.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';
import { cssBrand, jsonBrand } from './format.mjs';
import { nativeModule, themeCss } from './outputs.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = resolve(ROOT, 'dist');

/** The cascade order of packages/css/src/layers.css; the css package's test keeps the copies in step. */
export const LAYERS = ['reset', 'tokens', 'vendor', 'base', 'components', 'utilities'];

export const BRANDS = [
  { name: 'pulp', selector: ':root, [data-brand="pulp"]', component: true },
  { name: 'bitepals', selector: '[data-brand="bitepals"]', component: false },
];

StyleDictionary.registerFormat(cssBrand);
StyleDictionary.registerFormat(jsonBrand);

async function buildBrand({ name, selector, component }) {
  const sd = new StyleDictionary({
    usesDtcg: true,
    log: { verbosity: 'silent' },
    source: [
      resolve(ROOT, `tokens/primitives/${name}.json`),
      resolve(ROOT, `tokens/semantic/${name}.json`),
      // Component tokens are var() references into the semantic layer, so they
      // only need to exist once, on :root. Brand blocks restate nothing.
      ...(component ? [resolve(ROOT, 'tokens/component/*.json')] : []),
    ],
    platforms: {
      css: { transforms: [], files: [{ destination: `${name}.css`, format: 'pulp/css', options: { selector } }] },
      json: { transforms: [], files: [{ destination: `${name}.json`, format: 'pulp/json' }] },
    },
  });
  await sd.hasInitialized;
  const [css] = await sd.formatPlatform('css');
  const [json] = await sd.formatPlatform('json');
  return { name, css: css.output, json: JSON.parse(json.output) };
}

export async function render() {
  const brands = [];
  for (const brand of BRANDS) brands.push(await buildBrand(brand));

  const css = [
    '/* Generated by @pearpages/pulp-tokens from tokens/**.json. Do not edit: run `pnpm build:tokens`. */',
    '',
    '/* The layer order, restated in every stylesheet pulp ships: layers rank by first appearance. */',
    `@layer ${LAYERS.join(', ')};`,
    '',
    '@layer tokens {',
    '  /* Scheme axis. Colours are light-dark() pairs; color-scheme picks the side. */',
    '  :root { color-scheme: light dark; }',
    '  [data-scheme="light"] { color-scheme: light; }',
    '  [data-scheme="dark"] { color-scheme: dark; }',
    '',
    ...brands.map((brand) => `  /* Brand: ${brand.name} */\n${indent(brand.css)}`),
    '}',
    '',
  ].join('\n');

  const manifest = Object.fromEntries(brands.map((b) => [b.name, b.json]));
  const json = `${JSON.stringify(manifest, null, 2)}\n`;
  return { css, json, theme: themeCss(manifest), native: nativeModule(manifest) };
}

function indent(block) {
  return block.trimEnd().split('\n').map((line) => (line ? `  ${line}` : line)).join('\n') + '\n';
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const { css, json, theme, native } = await render();
  const targets = [
    [resolve(DIST, 'tokens.css'), css],
    [resolve(DIST, 'tokens.json'), json],
    [resolve(DIST, 'theme.css'), theme],
    [resolve(DIST, 'native.js'), native.esm],
    [resolve(DIST, 'native.cjs'), native.cjs],
    [resolve(DIST, 'native.d.ts'), native.dts],
  ];
  if (process.argv.includes('--check')) {
    const stale = targets.filter(([file, content]) => !existsSync(file) || readFileSync(file, 'utf8') !== content);
    if (stale.length) {
      console.error(`Token output is stale: ${stale.map(([f]) => f.replace(ROOT + '/', '')).join(', ')}. Run \`pnpm build:tokens\` and commit.`);
      process.exit(1);
    }
    console.log('Token output is up to date.');
  } else {
    mkdirSync(DIST, { recursive: true });
    for (const [file, content] of targets) writeFileSync(file, content);
    console.log(`Wrote ${targets.map(([f]) => f.replace(ROOT + '/', '')).join(', ')}`);
  }
}
