/**
 * The two outputs for consumers that do not read CSS custom properties the way a
 * browser stylesheet does (decision record 005). Both are views of the semantic tier
 * only, built from the same manifest as tokens.json:
 *
 *   theme.css   a Tailwind v4 `@theme inline reference` block: utility names over pulp's variables
 *   native      per brand `{ colors, radius, space, themeVars: { light, dark } }`, resolved values,
 *               for React Native / NativeWind and a Tailwind v3 config (ESM + CommonJS)
 */

const semantic = (manifest) => manifest.pulp.filter((token) => token.tier === 'semantic');
const variable = (token) => `var(${token.name})`;

/**
 * `inline`: a utility gets `var(--color-surface-base)` itself, so it follows brand and scheme at
 * run time. `reference`: Tailwind emits no variables of its own. Without it, 4.3 writes
 * `:root { --color-surface-base: var(--color-surface-base) }` into its `theme` layer, which is
 * declared after pulp's layers and therefore wins: a cycle that invalidates the token.
 */
export function themeCss(manifest) {
  const lines = [];
  for (const token of semantic(manifest)) {
    const [group, ...rest] = token.path;
    if (group === 'color' || group === 'radius' || group === 'shadow') lines.push(`  ${token.name}: ${variable(token)};`);
    // Tailwind's family namespace is --font-*, pulp's is --font-family-*.
    if (group === 'font' && rest[0] === 'family') lines.push(`  --font-${rest.slice(1).join('-')}: ${variable(token)};`);
  }
  return [
    '/* Generated by @pearpages/pulp-tokens from tokens/**.json. Do not edit: run `pnpm build:tokens`. */',
    '/* Tailwind v4: `@import "@pearpages/pulp-tokens/tokens.css"; @import "@pearpages/pulp-tokens/theme.css";` after `@import "tailwindcss"`. */',
    '/* Semantic tier only: bg-surface-base, text-text-muted, rounded-control, shadow-raised, font-display. */',
    '',
    '@theme inline reference {',
    ...lines,
    '}',
    '',
  ].join('\n');
}

/** "3px", "0.25rem", "calc(0.28rem * 6)" → px, as a number. React Native has no rem; 1rem is 16. */
export function toPx(value) {
  const calc = /^calc\((.+) \* ([\d.]+)\)$/.exec(value);
  if (calc) return round(toPx(calc[1]) * Number(calc[2]));
  const length = /^(-?[\d.]+)(px|rem)$/.exec(value);
  if (!length) throw new Error(`pulp tokens: cannot resolve "${value}" to px`);
  return round(Number(length[1]) * (length[2] === 'rem' ? 16 : 1));
}
const round = (n) => Math.round(n * 1000) / 1000;

function nest(target, path, value) {
  const [head, ...rest] = path;
  if (rest.length === 0) target[head] = value;
  else nest((target[head] ??= {}), rest, value);
  return target;
}

/** One brand: names as `var()` references for the config, and the values those variables take per scheme. */
export function nativeBrand(tokens) {
  const brand = { colors: {}, radius: {}, space: {}, themeVars: { light: {}, dark: {} } };
  for (const token of tokens.filter((candidate) => candidate.tier === 'semantic')) {
    const [group, ...rest] = token.path;
    if (group === 'color') {
      nest(brand.colors, rest, variable(token));
      brand.themeVars.light[token.name] = token.light ?? token.value;
      brand.themeVars.dark[token.name] = token.dark ?? token.value;
    } else if (group === 'radius' || group === 'space') {
      nest(brand[group], rest, variable(token));
      const px = `${toPx(token.value)}px`;
      brand.themeVars.light[token.name] = px;
      brand.themeVars.dark[token.name] = px;
    }
  }
  return brand;
}

export function nativeModule(manifest) {
  const brands = Object.fromEntries(Object.entries(manifest).map(([name, tokens]) => [name, nativeBrand(tokens)]));
  const header = '// Generated by @pearpages/pulp-tokens from tokens/**.json. Do not edit: run `pnpm build:tokens`.\n';
  const body = JSON.stringify(brands, null, 2);
  const names = Object.keys(brands);
  return {
    esm: `${header}const brands = ${body};\n\n${names.map((name) => `export const ${name} = brands.${name};`).join('\n')}\nexport default brands;\n`,
    // Metro and a Tailwind v3 config load this with require().
    cjs: `${header}module.exports = ${body};\n`,
    dts: `${header}type Nested = { [key: string]: string | Nested };
export interface NativeBrand {
  /** Semantic colour names as \`var(--color-…)\` references, nested by path: \`colors.surface.base\`. */
  colors: Nested;
  radius: Record<string, string>;
  space: Record<string, string>;
  /** What the variables resolve to per scheme (hex, px): NativeWind's \`vars(themeVars[scheme])\`. */
  themeVars: { light: Record<string, string>; dark: Record<string, string> };
}
${names.map((name) => `export declare const ${name}: NativeBrand;`).join('\n')}
declare const brands: { ${names.map((name) => `${name}: NativeBrand`).join('; ')} };
export default brands;
`,
  };
}
