/**
 * The published semantic token names: pulp's public API.
 *
 * A consumer writes `var(--color-action-primary)` in its own stylesheets — the
 * CV does, in 17 of them. Rename that token and nothing errors: CSS drops the
 * declaration and the consumer silently repaints. No build fails, no type
 * breaks, no test runs on their side. So the set is pinned here and asserted in
 * `build.test.mjs`.
 *
 * Editing this list is the deliberate act a rename should cost. Do it in the
 * same commit, and treat a removal or a rename as breaking: say so in the
 * changeset, and once pulp is 1.0, make it a major.
 *
 * Primitives are absent on purpose — they are private, and components may not
 * read them. Component tokens are absent too: they are documented per component
 * and travel with it.
 */
export const PUBLIC_SEMANTIC_TOKENS = [
  '--color-accent-1',
  '--color-accent-2',
  '--color-accent-3',
  '--color-accent-4',
  '--color-accent-5',
  '--color-accent-6',
  '--color-accent-7',
  '--color-accent-8',
  '--color-accent-on-1',
  '--color-accent-on-2',
  '--color-accent-on-3',
  '--color-accent-on-4',
  '--color-accent-on-5',
  '--color-accent-on-6',
  '--color-accent-on-7',
  '--color-accent-on-8',
  '--color-action-primary',
  '--color-action-primary-active',
  '--color-action-primary-hover',
  '--color-action-primary-quiet',
  '--color-action-secondary',
  '--color-action-secondary-hover',
  '--color-action-text',
  '--color-border-default',
  '--color-border-focus',
  '--color-border-strong',
  '--color-overlay-backdrop',
  '--color-status-error',
  '--color-status-error-active',
  '--color-status-error-hover',
  '--color-status-error-subtle',
  '--color-status-error-text',
  '--color-status-info',
  '--color-status-info-subtle',
  '--color-status-info-text',
  '--color-status-neutral',
  '--color-status-neutral-subtle',
  '--color-status-neutral-text',
  '--color-status-on-error',
  '--color-status-on-info',
  '--color-status-on-neutral',
  '--color-status-on-success',
  '--color-status-on-warning',
  '--color-status-success',
  '--color-status-success-subtle',
  '--color-status-success-text',
  '--color-status-warning',
  '--color-status-warning-subtle',
  '--color-status-warning-text',
  '--color-surface-base',
  '--color-surface-inverse',
  '--color-surface-overlay',
  '--color-surface-raised',
  '--color-surface-sunken',
  '--color-text-default',
  '--color-text-faint',
  '--color-text-muted',
  '--color-text-on-action',
  '--color-text-on-inverse',
  '--focus-ring-offset',
  '--focus-ring-width',
  '--font-family-body',
  '--font-family-display',
  '--font-family-mono',
  '--font-line-height-normal',
  '--font-line-height-tight',
  '--font-size-2xl',
  '--font-size-3xl',
  '--font-size-lg',
  '--font-size-md',
  '--font-size-sm',
  '--font-size-xl',
  '--font-size-xs',
  '--font-weight-medium',
  '--font-weight-regular',
  '--font-weight-semibold',
  '--layer-popover',
  '--layer-toast',
  '--layer-tooltip',
  '--motion-duration-base',
  '--motion-duration-fast',
  '--motion-easing-standard',
  '--radius-control',
  '--radius-full',
  '--radius-surface',
  '--shadow-overlay',
  '--shadow-raised',
  '--size-control-lg',
  '--size-control-md',
  '--size-control-sm',
  '--size-hairline',
  '--size-listbox-height',
  '--size-menu-width',
  '--size-popover-width',
  '--size-sheet-height',
  '--size-sheet-width',
  '--size-toast-width',
  '--size-toggle-lg',
  '--size-toggle-md',
  '--size-toggle-sm',
  '--space-1',
  '--space-2',
  '--space-3',
  '--space-4',
  '--space-5',
  '--space-6',
  '--space-7',
  '--space-8',
];
