/**
 * svg/<kebab-name>.svg → src/icons/<PascalName>.tsx + src/index.ts.
 *
 *   node scripts/generate.mjs          write
 *   node scripts/generate.mjs --check  fail if the committed output is stale
 *
 * The SVGs are the source of truth: 24×24, stroke-only, no fill, no width or
 * height. Every generated icon is decorative unless given a `title`, sized by
 * font-size, and coloured by currentColor.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SVG = resolve(ROOT, 'svg');
const OUT = resolve(ROOT, 'src/icons');

const pascal = (kebab) => kebab.split('-').map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join('');

/** Only simple stroke shapes are allowed, so the JSX translation stays trivial. */
const ALLOWED = /^<(path|circle|line|polyline|polygon|rect)\b[^>]*\/>$/;

function inner(svg, file) {
  const body = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>[\s\S]*$/, '').trim();
  return body
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
      if (!ALLOWED.test(line)) throw new Error(`${file}: only self-closing path/circle/line/polyline/polygon/rect elements are allowed, got: ${line}`);
      return `      ${line}`;
    })
    .join('\n');
}

function component(name, shapes) {
  return `// Generated from svg/${name}.svg by scripts/generate.mjs. Do not edit.
import type { IconProps } from '../types';

export function ${pascal(name)}({ title, ...props }: IconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      fill="none"
      stroke="currentColor"
      strokeWidth={2}
      strokeLinecap="round"
      strokeLinejoin="round"
      role={title ? 'img' : undefined}
      aria-hidden={title ? undefined : true}
      focusable="false"
      {...props}
    >
      {title ? <title>{title}</title> : null}
${shapes}
    </svg>
  );
}
`;
}

const names = readdirSync(SVG)
  .filter((file) => file.endsWith('.svg'))
  .map((file) => file.replace(/\.svg$/, ''))
  .sort();

const files = new Map();
for (const name of names) {
  files.set(`icons/${pascal(name)}.tsx`, component(name, inner(readFileSync(resolve(SVG, `${name}.svg`), 'utf8'), name)));
}
files.set(
  'index.ts',
  `// Generated by scripts/generate.mjs. Do not edit.
export type { IconProps } from './types';
${names.map((name) => `export { ${pascal(name)} } from './icons/${pascal(name)}';`).join('\n')}
`,
);

const check = process.argv.includes('--check');
const stale = [];
for (const [file, content] of files) {
  const path = resolve(ROOT, 'src', file);
  if (check) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== content) stale.push(file);
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
  }
}
if (!check) {
  // Drop generated icons whose SVG is gone.
  for (const file of readdirSync(OUT)) if (!files.has(`icons/${file}`)) rmSync(resolve(OUT, file));
  console.log(`Generated ${names.length} icons: ${names.map(pascal).join(', ')}`);
} else if (stale.length) {
  console.error(`Generated icons are stale: ${stale.join(', ')}. Run \`pnpm --filter @pearpages/pulp-icons generate\` and commit.`);
  process.exit(1);
} else {
  console.log('Generated icons are up to date.');
}
